version: 1
formatters:
  simple:
    format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
handlers:
    stream:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
    file:
        class: logging.handlers.RotatingFileHandler
        filename: 'test_model.log'
        maxBytes: 485760
        backupCount: 0
        formatter: simple
loggers:
    pmgsavvsie.test_model:
        level: INFO
        handlers: [file]
root:
    level: INFO
    handlers: [stream]
