name: Update troysieui version and tag

on:
  push:
    branches: 
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with: 
          repository: possemeeg/actions
          ref: main 
          path: actions
          token: ${{ secrets.GH_PAT }}
      - name: run tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pytest 
      - name: Bump and Tag
        uses: ./actions/cfgver
        with:
          config-file: setup.cfg
          tag-prefix: v
